---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: mobileyeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobileyeapp
  template:
    metadata:
      labels:
        app: mobileyeapp
    spec:
      containers:
        - name: mobileyeapp
          image: 394916145019.dkr.ecr.eu-central-1.amazonaws.com/mobileye-images
          ports:
          - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: mobileyeapp-service
spec:
  selector:
    app: mobileyeapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000

  type: LoadBalancer            
